Repository malcommac/SwiftDate, pull requests merged in 2019-09, with the labels that each got.

#672 Fix inverted meaning comments
  Sources/SwiftDate/Date/Date.swift
Labels: documentation

#683 Fix RelativeFormatterLanguage for correct relative time in Japanese
  Sources/SwiftDate/Formatters/RelativeFormatter/RelativeFormatterLanguage.swift
Labels: bug

#675 fixed spell Japanese language from js to ja
  Sources/SwiftDate/Formatters/RelativeFormatter/RelativeFormatterLanguage.swift
  Sources/SwiftDate/Formatters/RelativeFormatter/langs/zh_Hans.json
Labels: bug

#689 earlierDate and laterDate optimisation
  Sources/SwiftDate/Date/Date+Compare.swift
  Sources/SwiftDate/DateInRegion/DateInRegion+Compare.swift
  Tests/SwiftDateTests/TestDateInRegion+Compare.swift
Labels: enhancement

#676 Date difference and DateInRegion+Create.
  Sources/SwiftDate/Date/Date+Compare.swift
  Sources/SwiftDate/DateInRegion/DateInRegion+Create.swift
  SwiftDate.xcodeproj/project.pbxproj
  Tests/SwiftDateTests/TestDate.swift
Labels: enhancement
