Repository malcommac/SwiftDate, pull requests merged in 2019-03, with the labels that each got.

#647 httpheader formatter is not correct
  Sources/SwiftDate/Formatters/Formatter+Protocols.swift
  Sources/SwiftDate/Supports/Commons.swift
Labels: bug

#649 Relative Formatting: Use available relative values for a unit
  Sources/SwiftDate/Formatters/RelativeFormatter/RelativeFormatter.swift
Labels: bug, enhancement

#638 RoundingStrategy for RelativeFormatter.Gradation.Rule
  Sources/SwiftDate/Formatters/RelativeFormatter/RelativeFormatter+Style.swift
  Sources/SwiftDate/Formatters/RelativeFormatter/RelativeFormatter.swift
  SwiftDate.podspec
Labels: enhancement
