Repository malcommac/SwiftDate, pull requests merged in 2020-09, with the labels that each got.

#742 Support for non latin Serbian localization
  Sources/SwiftDate/Formatters/RelativeFormatter/langs/sr.json
Labels: enhancement

#694 Added support forDate position between 2 dates range (positionInRange)
  Sources/SwiftDate/Date/Date+Compare.swift
  Sources/SwiftDate/DateInRegion/DateInRegion+Compare.swift
  Tests/SwiftDateTests/TestDate.swift
  Tests/SwiftDateTests/TestDateInRegion+Compare.swift
Labels: enhancement

#695 Added support for Swift Package Manager (SwiftPM) 5.1
  Package.swift
Labels: enhancement

#700 Fix the behavior of dateAt(.startOfMonth)
  Sources/SwiftDate/DateInRegion/DateInRegion+Create.swift
  Tests/SwiftDateTests/TestDateInRegion+Create.swift
Labels: bug

#733 Minor typos fixes in documentation
  Documentation/1.Introduction.md
Labels: documentation

#710 Fixed grammar for Slovak translation
  Sources/SwiftDate/Formatters/RelativeFormatter/langs/sk.json
Labels: bug

#726 Fix date comparison using the .isSameMonth option
  Sources/SwiftDate/DateInRegion/DateInRegion+Compare.swift
Labels: bug

#707 Fixes traditional Chinese translation
  Sources/SwiftDate/Formatters/RelativeFormatter/langs/zh_Hant.json
Labels: bug

#703 Fix typos in README.md
  README.md
Labels: documentation

#705 Fix lint warning in spacing inside DateRelatedType
  Sources/SwiftDate/Formatters/ISOParser.swift
  Sources/SwiftDate/Supports/Commons.swift
Labels: design

#708 Fix typo in customFormatter of DataRepresentable
  Sources/SwiftDate/Date/Date.swift
Labels: design

#725 Fixed wrong timezone while setup a different SwiftDate.defaultRegion
  Sources/SwiftDate/Supports/Commons.swift
  SwiftDate.xcodeproj/xcshareddata/xcschemes/SwiftDate-iOS Tests.xcscheme
  Tests/SwiftDateTests/TestDate.swift
  Tests/SwiftDateTests/TestSwiftDate.swift
Labels: bug

#749 Crash - Force Unwrap
  Sources/SwiftDate/Foundation+Extras/TimeInterval+Formatter.swift
Labels: bug
